version-3-Done https://shna-rafeeq.github.io/iraq-bc-movies-project-students/
ReCoded-Org/iraq-bc-movies-project-students pull request #4
Opened 2020-06-27 22:51 UTC by shna-rafeeq

2020-06-30 08:10 UTC, MohammedAlabd requested changes
good job

2020-06-30 08:10 UTC, MohammedAlabd commented on bawan-shna-abdulrahman/src/App.js
> +  const [isLoading, setIsLoading] = useState(true);
This is so clever  to have an isLoading state

2020-06-30 08:10 UTC, MohammedAlabd commented on bawan-shna-abdulrahman/src/Components/DropdownCategories.js
> +  }, [SEARCH_URL_CATEGORIES]);
I think the app will still working even if you removed the variable inside the square brackets 
so what is this for?

2020-06-30 08:10 UTC, MohammedAlabd commented on bawan-shna-abdulrahman/src/Components/DropdownCategories.js
> +        console.log(data);
always remove the unused consol.logs or comments from your PR

2020-06-30 08:10 UTC, MohammedAlabd commented on bawan-shna-abdulrahman/src/Components/Main.js
> +  const movies = props.movies;
you can use the destructured here like this
```suggestion
  const {movies} = props
```

2020-06-30 08:10 UTC, MohammedAlabd commented on bawan-shna-abdulrahman/src/Components/MovieGrid.js
> +import { Row } from "react-simple-flex-grid";
Is it possible to use react-bootstrap for rows and grid things?

checkout this link
[React-Bootstrap Grid System](https://react-bootstrap.github.io/layout/grid/ )

2020-06-30 08:10 UTC, MohammedAlabd commented on bawan-shna-abdulrahman/src/Components/MovieGrid.js
> +              src={"https://image.tmdb.org/t/p/original" + movie.backdrop_path}
try to use the template strings here
```suggestion
              src={`https://image.tmdb.org/t/p/original${movie.backdrop_path}`}
```

2020-06-30 08:10 UTC, MohammedAlabd commented on bawan-shna-abdulrahman/src/Components/Search.js
> +    console.log(category);
remove this console.log

2020-06-30 08:10 UTC, MohammedAlabd commented on bawan-shna-abdulrahman/src/Components/Search.js
> +    if (!props.isLoading) return;
you can call the `fetchMovie` function in the onSubmit function so you don't have to pass it as a dependencies for the useEffect then you can remove the condition in `line 27` because you will not have to use it after that.

2020-07-01 06:38 UTC, shna-rafeeq commented on bawan-shna-abdulrahman/src/Components/Main.js
> +  const movies = props.movies;
yeh thank you didnt know about that

2020-07-01 06:46 UTC, shna-rafeeq commented on bawan-shna-abdulrahman/src/Components/Search.js
> +    if (!props.isLoading) return;
i tried what you say but at first it will not show the popular movies and the spinner will spin even if you didnt write something.

2020-07-04 10:31 UTC, closed without merging